### ISSUE TITLE
getopt_long not implemented

### ISSUE THREAD

**Issue by darrenkopp** [darrenkopp/sassc-win#1]
once this is implemented, it will compile on windows. you can do it currently by changing getopt_long to getopt and it will compile and run.

**Comment by am11** [comment]
THANKS a lot @darrenkopp !! You rock! :100: :+1: 

I will take a stab at it soon. :smiley: 

/cc @mgreter, @xzyfer

**Comment by am11** [comment]
@QuLogic, is there an STL equivalent of getopt and getopt_long in C++11, which all cpp11 compatible compilers support?

**Comment by am11** [comment]
This is fixed by 1d29e0f. I found the repo: https://github.com/alex85k/wingetopt/.

The compilation was successful. We don't need any extra guard like `unistd.h`.

**Comment by darrenkopp** [comment]
awesome. nicely done.

**Comment by am11** [comment]
@darrenkopp, can you please register the repo at appveyor? https://ci.appveyor.com/projects/darrenkopp/sassc-win/

**Comment by am11** [comment]
You can also sign in with GitHub on Appveyor. :)

**Comment by darrenkopp** [comment]
done. https://ci.appveyor.com/project/darrenkopp/sassc-win

**Comment by am11** [comment]
Brilliant! :+1:

**Comment by am11** [comment]
Success! https://ci.appveyor.com/project/darrenkopp/sassc-win/build/1.0.14 :smile: :star:

**Comment by mgreter** [comment]
:+1:

**Comment by am11** [comment]
Now it is testing against four configurations: Release Win32 and Release Win64.

Those are the custom configuration names in VS project file, which are used as is in appveyor.yml.

For more configuration options, see: http://www.appveyor.com/docs/build-configuration.

**Comment by am11** [comment]
I have merged the functionality of libsass and sassc travis script.

The build is successful, after that it hooks into ruby and run the command: https://ci.appveyor.com/project/darrenkopp/sassc-win/build/1.0.28/job/hvcn4p415ryelkfw

It fails the test, where it says: `@import "http://fonts.googleapis.com/css?family=Droid+Sans";` and expect the same. Notice that this is CSS3 import, so shouldn't be processed at all. But it is failing with a weird error:

``` powershell
C:/projects/sassc-win/sassc-win/sass-spec/spec/libsass-todo-tests/http_import/input.scss:1: 
file to import not found or unreadable: "http://fonts.googleapis.com/css?family=Droid+Sans"
Current dir: C:/projects/sassc-win/sassc-win/sass-spec/spec/libsass-todo-tests/http_import/
Command exited with code 4
```

@mgreter , @xzyfer, any idea if it is a libsass issue or sass-spec.rb ? It seems like libsass is trying to read from URL and the runtime is not letting it. In which case, it would be a libsass issue that it should try to access the file in CSS3 `@import` scenario.

**Comment by am11** [comment]
Or could it be this issue: http://stackoverflow.com/a/15591530? Do we need compass gem for running sassc tests?

**Comment by darrenkopp** [comment]
I would be quite surprised if you did

**Comment by am11** [comment]
Yes! It shouldn't read CSS3 `@import` file in first place, especially the font URL..

**Comment by darrenkopp** [comment]
Agreed, though I did have someone recently say something to me similar where it was embedding s normal CSS file, but I never verified if that's what was actually happening or if that's just what it sounded like

**Comment by am11** [comment]
@darrenkopp, do you support "custom functions" features of libsass in libsass-net downstream? @mgreter shared some useful bits for node-sass https://github.com/sass/node-sass/issues/332, but unfortunately, I didn't get time to wrap my head around it yet. :-1:

**Comment by darrenkopp** [comment]
Unlikely, I just wrap it purely, no more, no less.

**Comment by am11** [comment]
That would be interesting to implement custom functions in [Web Essentials](https://github.com/madskristensen/webEssentials2013/), when node-sass get this support. WE is now using both node-sass and ruby sass: https://github.com/madskristensen/WebEssentials2013/blob/641978629c51f824f2dffe3ce56b2c62aced1256/EditorExtensions/Resources/server/services/. Perhaps, we would let the users add `sass-custom-functions.js` in solution items and enable reference.js, so they can manage in multiple files. :D

**Comment by am11** [comment]
Probably it's worth mentioning that the vcxproj file is now updated with latest libsass changes. I included `cencode.c`, `json.hpp` and `json.cpp` to the project and it compiled with no errors (just 75 warnings)! :smile:

**Comment by am11** [comment]
Isn't [that test](https://github.com/sass/sass-spec/blob/701637b5733ee6c1ad739dafa7678fb774324a4c/spec/libsass-todo-tests/http_import/input.scss) incorrect? 

Shouldn't it be: `@import url("http://fonts.googleapis.com/css?family=Droid+Sans")`.

Even the [expected output](https://github.com/sass/sass-spec/blob/701637b5733ee6c1ad739dafa7678fb774324a4c/spec/libsass-todo-tests/http_import/expected_output.css) isn't CSS3?

See http://stackoverflow.com/q/26349982/

I have [used](https://github.com/darrenkopp/sassc-win/commit/aecff0cac3818bdbf882c2b32c8ccf5c52950175) the [--ignore-todo flag](https://github.com/sass/sass-spec/blob/701637b5733ee6c1ad739dafa7678fb774324a4c/lib/sass_spec/cli.rb#L45) now.

Fingers crossed ..

**Comment by darrenkopp** [comment]
No, that test is correct. It's supposed to just pass through.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

**Comment by am11** [comment]
Thanks for the link @darrenkopp! It seems like that is not covered by libsass yet.

**BREAKING NEWS** All tests are passing now: https://ci.appveyor.com/project/darrenkopp/sassc-win/build/1.0.29. Yay :grey_exclamation::grey_exclamation: 
Travis-ci build also runs same amount of tests: https://travis-ci.org/sass/libsass/jobs/39661259. :+1: (but I couldn't find the `--ignore-todo` flag in their script though)

Now we need to figure out a way to split appveyor.yml, and push part of it to libsass. So, whenever commit is made in libsass, the Appveyor's libsass account clone into this repo and get the other half (like it does with sassc CLI atm). But that is something I haven't figured yet, as we are using solution based and compiling everything at once and running the test all from one place. I think libsass' appveyor.yml should only clone into our repo and trigger our appveyor.yml. I don't know how to do that yet. :sunglasses:

**Comment by am11** [comment]
Hello @darrenkopp, I have an unrelated question to this topic:

I am trying to figure out the correct compiler switches to build [node-sass](https://github.com/sass/node-sass) project on Windows. I looked into the docs and there are plenty of them. We already have the build system in place, which builds binaries for nodejs using VS2013's `cl.exe`, that is; [node-gyp](https://github.com/TooTallNate/node-gyp).

Here is the configuration for VS: [binding.gyp#L69-L84](https://github.com/sass/node-sass/blob/7b7fde90325f0dfedf17143553ffe31de00bb244/binding.gyp#L69-L84).

There are reports that the binary isn't working on Windows 7 x86, which I built on Win8.1.1 x64 running nodejs x86. 

Is there any special compiler flag we need to set, which guarantees that the binary would run on Windows 7 as good as 8?

Thanks.

**Comment by darrenkopp** [comment]
@am11 and you are sure they have visual c++ 2013 redistributable runtime? http://www.microsoft.com/en-us/download/details.aspx?id=40784

That's the only thing I can think of that would cause a problem, should work on windows 7 fine, but I know someone running Win 7 x64 that could probably run it to test.

**Comment by am11** [comment]
Actually it was this bug reported for node-sass latest released version 1.2.2 https://github.com/sass/node-sass/issues/524 which states the issue. I don't have Windows 7 machine. Is that necessary? Can we make the binary independent of dependency on redist runtime? 

@davetgreen, momentarily, can you confirm that you have C++2013 runtime and if not; installing it fixes the issue?

**Comment by darrenkopp** [comment]
Yeah, I'd assume that it should work anywhere, but I'm not a c++ developer so I don't really know. I'd be surprised if Win7 didn't work.

**Comment by am11** [comment]
Thanks for your help! I will try to get my hands on a Windows 7 32-bits VM and test it out. :)
