### ISSUE TITLE
Distributing complied binaries to the public.

### ISSUE THREAD

**Issue by SteffanDonal** [darrenkopp/sassc-win#2]
I spent a longer-than-required time looking for and eventually finding this wrapper - and now that I've got it, I'd like to distribute compiled versions of the source through a simple webpage. Correctly attributed of course, and links back to this page, etc.

Is this okay?

**Comment by am11** [comment]
@Ruirize, this project is kind of outdated, as [it is merged](https://github.com/sass/sassc/pull/91/) in the actual repo: https://github.com/sass/sassc.

So the quickest way to build sassc executable would be:
- Download libsass archieve https://github.com/sass/libsass/archive/master.zip and extract.
- Download sassc archeive https://github.com/sass/sassc/archieve/master.zip and extract inside libsass dir root.
- Open `libsass/sassc/win/sassc.sln` in VS2013 Update 4+ and build, it will generate the executable at `libsass/sassc/bin/sassc.exe`.

I think that executable is open for distribution. See the contribution agreement of sassc: https://github.com/sass/sassc#contribution-agreement.

**Comment by SteffanDonal** [comment]
Ah, I see it was added 15 days ago. That'll be why I missed it. Thank you!

I'll close this issue.
